name: "DSC Configuration Apply"

on:
  push:
    branches: [ test ]  

jobs:
  harden-windows2019:
    runs-on: windows-2019

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3  

        - name: "Install Required DSC Modules"
          run: |
            Install-Module -Name PSDesiredStateConfiguration -Force -Scope CurrentUser
            Install-Module -Name AuditPolicyDsc -Force -Scope CurrentUser
            Install-Module -Name SecurityPolicyDsc -Force -Scope CurrentUser
          shell: pwsh
    
        - name: "Run DSC Configuration"
          run: |
            # Ensure the script is executable
            chmod +x .\Hardening_WindowsServer2019.ps1
            # Execute the DSC script
            .\scripts\Hardening_WindowsServer2019.ps1
          shell: pwsh