name: "DSC Configuration Apply"

on:
  push:
    branches: [ test ]  

jobs:
  harden-windows2019:
    runs-on: windows-2019

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3  

        - name: "Install Required DSC Modules"
          run: |
            Install-Module -Name PSDesiredStateConfiguration -Force -Scope CurrentUser
            Install-Module -Name AuditPolicyDsc -Force -Scope CurrentUser
            Install-Module -Name SecurityPolicyDsc -Force -Scope CurrentUser
          shell: pwsh

        - name: "Check if the target Windows Server 2019 machine already has the SecurityPolicyDsc module installed"
          run: |
            Get-Module -ListAvailable | Where-Object {$_.Name -eq 'SecurityPolicyDsc'}
          shell: pwsh
          
        - name: "Configure and Start WinRM"
          run: |
            # Ensure WinRM is properly configured
            winrm quickconfig -quiet
            # Allow basic authentication
            winrm set winrm/config/service/auth @{Basic="true"}
            # Allow unencrypted traffic
            winrm set winrm/config/service @{AllowUnencrypted="true"}
          shell: cmd

        - name: "Run DSC Configuration"
          run: |
            # Ensure the script is executable
            # chmod +x .\scripts\Hardening_WindowsServer2019.ps1
            # Execute the DSC script
            .\scripts\Hardening_WindowsServer2019.ps1
          shell: pwsh