name: "powercli CI workflow windows"


on:
  push:
    branches: [ test ]



jobs:

  windows-latest-pwsh-scripts:
    name: "powercli- windows-latest Microsoft Windows Server 2019 Datacenter"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "powershell version" 
      run: $PSVersionTable
    # - name: "PowerCLI - MajorityElement without modules" 
    #   run: .\scripts\MajorityElement.ps1    
    - name: "PowerCLI - MajorityElement with modules" 
      run: .\scripts\MajorityElement_module.ps1   
    - name: "PowerCLI - Find non repeating first char with modules" 
      run: .\scripts\FirstNonRepeatingChar.ps1                

