name: "powercli CI workflow windows"


on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression schedules the workflow to run every 5 minutes
  
  push:
    branches: [ main ]



jobs:

  windows-latest-pwsh-scripts:
    name: "powercli- windows-latest Microsoft Windows Server 2019 Datacenter"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "powershell version" 
      run: $PSVersionTable
    - name: "PowerCLI - MajorityElement" 
      run: .\scripts\MajorityElement.ps1    
    - name: "PowerCLI - MajorityElement with modules" 
      run: .\scripts\MajorityElement_module.ps1            

